### ISSUE TITLE
path to OpenSSL... not found

### ISSUE THREAD

**Issue by Hostile** [wraith/wraith#102]
Ubuntu 14.04

`checking for sys/prctl.h... yes
checking for path to OpenSSL... not found
configure: error: OpenSSL is required.

root@ns1:~/wraith-v1.4.6# apt install openssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by bdrewery** [comment]
Do you have the openssl-dev package? The openssl package won't have the headers by default.

**Comment by Hostile** [comment]
yes sorted it works now thanks
