### ISSUE TITLE
wraith, crontab, pid-file and same pid

### ISSUE THREAD

**Issue by fred0r** [wraith/wraith#104]
it just happend that wraith wasnt able to restart via cron because another process had the same pid as the killed wraith-process had in its '...'-folder after a reboot of the system.
so the crontab never started a new wraith-process.
debian jessie with 4.6.3.x64-kernel

**Comment by bdrewery** [comment]
Using file locking we can probably detect if the process is still running. The problem will be for upgrades though since the old pidfiles won't be locked.

**Comment by fred0r** [comment]
this sounds like a very special condition - perhaps using a second 'update.pid'-file ?

**Comment by fred0r** [comment]
I dont know if this matters - but I'm running my wraith hub inside a 'nspawn-session'

**Comment by bdrewery** [comment]
What is that?

**Comment by fred0r** [comment]
Some sort of Virtualisation/Chroot from systemd:
https://wiki.archlinux.org/index.php/Systemd-nspawn.
The PIDs within nspawn are shared/mapped with the host.
Inside the nspawn-session the wraith-process gets a pid below 100.
Since some time i changed that a normal user is able to see all processes (proc / hidepid=2) in fstab.
With this users only see their own processes.
It didnt happen for a while now - perhaps before wraith was able 'to see' the nspawn-hosts pids.
i will keep a look at it.
