### ISSUE TITLE
wraith stalling mid-run on OS X

### ISSUE THREAD

**Issue by CharlesBelov** [wraith/wraith#106]
I have just installed wraith on a Mac OS X 10.11.6 with CasperJS and am attempting my first successful run, with the following command:

wraith capture /Users/[userid]/wraith/configs/sfmta_full.yaml 2> errors.txt

It starts well, with the following messages:

WARN: You have specified a `history_dir` in your config, but this is used in `history` mode, NOT `capture` mode. See the docs at http://bbc-news.github.io/wraith/
Config validated. No serious issues found.
Creating Folders
SAVING IMAGES

Followed by 2095 (first try) or 205 (second try) occurrences of:

Snapping [page] at: [screen size]

(I'm expecting Snapping to occur 139 pages x 10 screen sizes x 2 websites = 2780 times)

At some point, it stalls. The ps command shows it is still running, but it seems to be just sitting there 20 minutes later :

20283 ttys001    0:00.41 /System/Library/Frameworks/Ruby.framework/Versions/2.0
20325 ttys001    0:16.05 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20328 ttys001    0:16.17 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20329 ttys001    0:04.62 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20330 ttys001    0:05.00 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20331 ttys001    0:15.14 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20332 ttys001    0:14.96 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20335 ttys001    0:02.53 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20336 ttys001    0:04.23 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin

and a several minutes later

20283 ttys001    0:00.41 /System/Library/Frameworks/Ruby.framework/Versions/2.0
20325 ttys001    0:16.89 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20328 ttys001    0:17.02 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20329 ttys001    0:05.47 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20330 ttys001    0:05.84 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20331 ttys001    0:16.09 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20332 ttys001    0:15.90 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20335 ttys001    0:03.48 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20336 ttys001    0:05.18 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin

Casper is still using time, but the Ruby framework isn't.

Unlike on Ubuntu, I never see a process called wraith.

If I look at the files that have been created on the 205 "Snapping" run:

9 folders have the expected 20 snapshots each
2 folders each have 10 snapshots: a snapshot from each site for five of the screen sizes
1 folder has 5 snapshots: a snapshot from one site for the same five screen sizes

Several minutes later, Casper is still using time, but no new images:

20283 ttys001    0:00.41 /System/Library/Frameworks/Ruby.framework/Versions/2.0
20325 ttys001    0:17.73 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20328 ttys001    0:17.86 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20329 ttys001    0:06.30 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20330 ttys001    0:06.68 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20331 ttys001    0:17.02 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20332 ttys001    0:16.84 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20335 ttys001    0:04.42 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin
20336 ttys001    0:06.10 phantomjs /usr/local/Cellar/casperjs/1.1.3/libexec/bin

The config file is the exact same one that is working fine on Ubuntu.

My OS X installation was mostly but not completely routine:
I installed imagemagick and casperJS using homebrew in the default location (/usr/local/)
I installed wraith using gem install wraith
Wraith version is 3.2.1

Only thing out of the ordinary was that my initial gem install wraith failed because nokogiri complained that a library it needed wasn't present, and to reinstall nokogiri using 

gem install nokogiri -- --use-system-libraries

I did so, and then "gem install wraith" worked.

However, if I do a "gem list" it shows two versions of nokogiri installed:

nokogiri (1.6.8, 1.5.6)

The only CasperJS command in the config file is:

before_capture: 'javascript/wait--casper.js'

which executes:

module.exports = function (casper, ready) {
    // make Wraith wait a bit longer before taking the screenshot
    casper.wait(10000, ready); // you MUST call the ready() callback for Wraith to continue
}

Any ideas on how to unstick wraith?

**Comment by bdrewery** [comment]
Sorry you have the wrong project. This isn't a ruby or tracing project. It is an IRC bot.

You want: https://github.com/BBC-News/wraith
