### ISSUE TITLE
Add Channelkey to Botnet

### ISSUE THREAD

**Issue by fred0r** [wraith/wraith#125]
It would be nice if a User adds a Key (+k) manually to a Chan, that this Key is also known/saved on the Botnet afterwards.

**Comment by fred0r** [comment]
But that shouldnt make the bots change the chanmode-settings to '+k' automatically.

**Comment by bdrewery** [comment]
`.bl channel #chan` will show the key.
`.bl getkey #chan` might do it too.

**Comment by fred0r** [comment]
At that time writing this issue, the problem existed for me, but know i did some test and the manually set Channelkey was 'known' to the botnet afterwards.
