### ISSUE TITLE
Fish needs auto KEYX on decrypt error

### ISSUE THREAD

**Issue by bdrewery** [wraith/wraith#74]
## in query

<pre>
08:29:16 [bryan] auth? *
08:29:20 -!- FiSH: Sent my DH1080 public key to wraithtcl, waiting for reply ...
08:29:21 -!- FiSH: Key for wraithtcl successfully set!
08:29:22 [bryan] auth? *
08:29:25 [wraithtcl] auth. wtest2 *
</pre>

## on bot

<pre>
 [14:29:16] (wtest2) [bryan!bryan@host] +OK O.czD.Jf8wN. 
</pre>

**Comment by ducch** [comment]
isn't this a duplicate of #23?

**Comment by bdrewery** [comment]
e21e1336e4972b097389507f9ff9ddfd08fb6dc5 should have covered it

**Comment by bdrewery** [comment]
Ah, not quite.
