### ISSUE TITLE
binary updating with mmap doesn't work with NFS on FreeBSD 11

### ISSUE THREAD

**Issue by bdrewery** [wraith/wraith#99]
`pid 80680 (wraith), uid 1298, was killed: text file modification`

**Comment by Faded** [comment]
Brian, you are incredible. I can't believe after all these years that you're still working on the wraith bot. I remember buying the bot from you when you first made it. -shield@EFNet(nolonger)

**Comment by bdrewery** [comment]
Thanks! I hack on it off and on every now and then. Development really died down around 2010 though.

**Comment by bdrewery** [comment]
This is unfixable and the system no longer uses NFS.
